apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: antoniolopesg/hello-world:v5.2
          envFrom:
            - configMapRef:
                name: server-env
            - secretRef:
                name: server-secret
          volumeMounts:
            - mountPath: /myfamily
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"