apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: antoniolopesg/hello-world:v5.3
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 15
          envFrom:
            - configMapRef:
                name: server-env
            - secretRef:
                name: server-secret
          volumeMounts:
            - mountPath: /myfamily
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"